#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2024 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#

declare -g ARCH="riscv64"
declare -g LINUXFAMILY="ky"
declare -g GOVERNOR="performance"

# U-Boot
declare -g BOOTSOURCE="https://github.com/orangepi-xunlong/u-boot-orangepi.git"
declare -g BOOTSOURCE="https://codeberg.org/sven-ola/u-boot-orangepi-ky.git"
declare -g BOOTBRANCH="commit:89bff4a7e4cadfb5f130edb1ec44c39bff20a427"
declare -g BOOTBRANCH="branch:v2022.10-ky"
declare -g BOOTPATCHDIR="${BOOTPATCHDIR:-"u-boot-ky"}"
declare -g BOOTDIR="u-boot-ky"
declare -g UBOOT_TARGET_MAP=";;bootinfo_emmc.bin bootinfo_sd.bin bootinfo_spinor.bin FSBL.bin u-boot-env-default.bin u-boot-opensbi.itb"
declare -g BOOTCONFIG="x1_defconfig" # Boot with generic Ky X1 config

# Linux
case "${BRANCH}" in
	current)
		declare -g KERNELSOURCE="https://github.com/orangepi-xunlong/linux-orangepi.git"
		declare -g KERNELSOURCE="https://codeberg.org/sven-ola/linux-orangepi-ky"
		declare -g KERNELBRANCH="commit:ae9e974d3e19f460b6397bfe8f0f1417a073ce05"
		declare -g KERNELBRANCH="branch:orange-pi-6.6-ky"
		declare -g EXTRAWIFI="no" # WiFi drivers are already included in the kernel
		declare -g KERNEL_MAJOR_MINOR="6.6"
		declare -g LINUXCONFIG="linux-${LINUXFAMILY}-current"
		;;
esac

# Note:
# In difference to Banana Pi F3, OpenSBI is not compiled
# separately, but as part of the uboot tree which in turn
# is then seems integrated within u-boot-opensbi.itb file.

write_uboot_platform() {
	if [ -b "${2}boot0" ]; then
		echo "Copy u-boot to eMMC"
		echo 0 > "/sys/block/${2##*/}boot0/force_ro"
		sleep .50
		dd if="${1}/bootinfo_emmc.bin" of="${2}boot0"
		dd if="${1}/FSBL.bin of=${2}boot0" seek=512 bs=1
		sync
		echo 1 > "/sys/block/${2##*/}boot0/force_ro"
	else
		echo "Copy u-boot to SD card"
		dd if="${1}/bootinfo_sd.bin" of="${2}" conv=notrunc status=none
	fi
	dd if="${1}/FSBL.bin" of="${2}" seek=256 conv=notrunc status=none
	dd if="${1}/u-boot-env-default.bin" of="${2}" seek=768 conv=notrunc status=none
	dd if="${1}/u-boot-opensbi.itb" of="${2}" seek=1664 conv=notrunc status=none
	sync
}

write_uboot_platform_mtd() {
	if [ -b /dev/mtdblock0 ]; then
		dd if="${1}/bootinfo_spinor.bin" of=/dev/mtdblock0 status=none
		dd if="${1}/FSBL.bin" of=/dev/mtdblock2 status=none
		dd if="${1}/u-boot-env-default.bin" of=/dev/mtdblock3 status=none
		dd if="${1}/u-boot-opensbi.itb" of=/dev/mtdblock5 status=none
		sync
	fi
}

# Note:
# https://bianbu-linux.spacemit.com/en/faqs/ states, that we need to
# load esos.elf for the Real Time CPU (I2C+S, UART, CAN, PWM, SPI...)
# In difference to the Banana Pi F3's FW_LOADER kernel module, for the
# Ky X1 we install via BSP and load it from initramfs::/lib/firmware

family_tweaks_bsp() {
	mkdir -p ${destination}/usr/lib/firmware
	cp ${SRC}/packages/bsp/ky/esos.elf ${destination}/usr/lib/firmware/
}
