# ./compile.sh CPUTHREADS=$(nproc) bpif3

BOARD=bananapif3
BRANCH=current
RELEASE=trixie

KERNEL_CONFIGURE=no
ARTIFACT_IGNORE_CACHE=yes
BUILD_DESKTOP=no
BUILD_MINIMAL=yes

PREFER_DOCKER=yes
KERNEL_GIT=shallow
SKIP_ARMBIAN_REPO=yes
