# ./compile.sh bpi1

BOARD=bananapi
BRANCH=current
RELEASE=trixie

KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
KERNEL_BTF=no
BUILD_DESKTOP=no
BUILD_MINIMAL=yes

#ARTIFACT_IGNORE_CACHE=yes
SKIP_ARMBIAN_REPO=yes
DOCKER_ARMBIAN_BASE_IMAGE=debian:trixie
