# ./compile.sh opiz3

BOARD=orangepizero3
BRANCH=current
RELEASE=trixie

KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
KERNEL_BTF=no
BUILD_DESKTOP=no
BUILD_MINIMAL=yes

#ARTIFACT_IGNORE_CACHE=yes
SKIP_ARMBIAN_REPO=yes
