# ./compile.sh CPUTHREADS=$(nproc) rpi64

BOARD=rpi4b
BRANCH=current
RELEASE=trixie

KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
BUILD_DESKTOP=no
BUILD_MINIMAL=yes

#ARTIFACT_IGNORE_CACHE=yes
SKIP_ARMBIAN_REPO=no
