# ./compile.sh CPUTHREADS=$(nproc) opirv2

BOARD=orangepirv2
BRANCH=current
RELEASE=trixie

KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
BUILD_DESKTOP=no
BUILD_MINIMAL=yes

#ARTIFACT_IGNORE_CACHE=yes
SKIP_ARMBIAN_REPO=yes
