# ./compile.sh CPUTHREADS=$(nproc) bpi2

BOARD=bananapim2ultra
BRANCH=current
RELEASE=trixie

KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
#ARTIFACT_IGNORE_CACHE=yes
BUILD_DESKTOP=no
BUILD_MINIMAL=yes

SKIP_ARMBIAN_REPO=yes
