# ./compile.sh CPUTHREADS=$(nproc) bpi1

BOARD=bananapi
BRANCH=current
RELEASE=trixie

KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
BUILD_DESKTOP=no
BUILD_MINIMAL=yes

#ARTIFACT_IGNORE_CACHE=yes
SKIP_ARMBIAN_REPO=yes
